import { randomUUID } from 'node:crypto';
import { expect, type Page } from '@playwright/test';
import { test } from './fixtures.js';
import { administrator, changePassword, login, register } from './auth-helpers.js';
import { observeBrowserErrors } from './browser-errors.js';
async function searchAccount(page: Page, email: string) {
 await page.getByLabel('Search account email', { exact: true }).fill(email); await page.getByRole('button', { name: 'Apply filters', exact: true }).click(); const row = page.getByRole('row').filter({ hasText: email }); await expect(row).toBeVisible(); return row;
}
test('platform admin creates a tenant and host, controls access, and preserves records when deleting the tenant', async ({ page, browser, baseURL, browserErrors }, testInfo) => {
 test.setTimeout(90000); const errors = browserErrors; await administrator(page);
 const slug = `browser-${randomUUID()}`; const name = `Browser tenant ${randomUUID()}`; const hostEmail = `new-host-${randomUUID()}@example.test`; const temp = `Temporary new host ${randomUUID()}!`; const changed = `Changed new host ${randomUUID()}!`; const title = `A home in ${name}`;
 await page.getByRole('link', { name: 'Create tenant', exact: true }).last().press('Enter'); await page.getByLabel('Tenant name', { exact: true }).focus();
 for (const [label, value] of [['Tenant name', name], ['Portal slug', slug], ['Business time zone', 'Europe/Berlin'], ['Brand colour', '#ffffff'], ['Contact email', 'contact@example.test']]) {
  await expect(page.getByLabel(label!, { exact: true })).toBeFocused(); await page.keyboard.press('ControlOrMeta+A'); await page.keyboard.insertText(value!); await page.keyboard.press('Tab');
 }
 await expect(page.getByRole('button', { name: 'Create tenant', exact: true })).toBeFocused(); await page.keyboard.press('Enter');
 await expect(page.getByLabel('Portal slug', { exact: true })).toHaveAttribute('readonly', ''); const tenantId = new URL(page.url()).pathname.split('/').at(-1)!; await page.getByRole('link', { name: 'Manage accounts', exact: true }).click();
 await page.getByRole('button', { name: 'Create host', exact: true }).click(); await page.getByLabel('Host name', { exact: true }).fill('Browser host'); await page.getByLabel('Email address', { exact: true }).fill(hostEmail); await page.getByLabel('Temporary password', { exact: true }).fill(temp); await page.getByLabel(/I verified.*identity/).check(); await page.getByRole('button', { name: 'Create host account', exact: true }).click(); await expect(page.getByText(/Host created\./)).toBeVisible(); await expect(page.getByLabel('Temporary password', { exact: true })).not.toBeVisible();
 const context = await browser.newContext({ baseURL, viewport: page.viewportSize() }); const host = await context.newPage(); observeBrowserErrors(host, errors);
 try {
  await login(host, slug, hostEmail, temp); await changePassword(host, temp, changed, slug); await host.getByRole('link', { name: 'Host workspace', exact: true }).click(); await host.getByRole('link', { name: 'Create listing', exact: true }).click();
  for (const [label, value] of Object.entries({ Title: title, Description: 'Created through tenant administration.', City: 'Berlin', 'Country code': 'DE', Latitude: '52.52', Longitude: '13.4', 'Maximum guests': '2', Bedrooms: '1', 'Price per night (€)': '95.00' })) await host.getByLabel(label, { exact: true }).fill(value);
  await host.getByRole('button', { name: 'Create listing', exact: true }).click(); await expect(host.getByRole('heading', { name: 'Edit listing', exact: true })).toBeVisible(); const listingId = new URL(host.url()).pathname.split('/').at(-1)!;
  const visitorContext = await browser.newContext({ baseURL, viewport: page.viewportSize() }); const visitor = await visitorContext.newPage(); observeBrowserErrors(visitor, browserErrors);
  try { await visitor.goto(`/${slug}`); await expect(visitor.getByRole('link', { name: title, exact: true })).toBeVisible(); await visitor.screenshot({ path: testInfo.outputPath('new-tenant-portal.png'), fullPage: true }); await visitor.goto('/citystays'); await expect(visitor.getByRole('link', { name: title, exact: true })).toHaveCount(0); expect((await visitor.request.get(`/api/v1/t/citystays/listings/${listingId}`)).status()).toBe(404); } finally { await visitorContext.close(); }
  await host.getByRole('link', { name: 'View public listing', exact: true }).click(); await expect(host.getByRole('heading', { name: title, exact: true })).toBeVisible();
  const row = page.getByRole('row').filter({ hasText: hostEmail }); await row.getByRole('button', { name: 'Disable', exact: true }).click(); await expect(page.getByText(/entire tenant account will be disabled/)).toBeVisible(); await page.getByRole('button', { name: 'Confirm disable', exact: true }).press('Enter'); await expect(row.getByRole('button', { name: 'Re-enable', exact: true })).toBeVisible();
  expect((await host.request.get(`/api/v1/t/${slug}/auth/me`)).status()).toBe(401); await host.goto(`/${slug}/host/listings`); await expect(host).toHaveURL(new RegExp(`/${slug}/login`));
  await row.getByRole('button', { name: 'Re-enable', exact: true }).click(); await page.getByRole('button', { name: 'Confirm re-enable', exact: true }).click(); await expect(row.getByRole('button', { name: 'Disable', exact: true })).toBeVisible(); expect((await host.request.get(`/api/v1/t/${slug}/auth/me`)).status()).toBe(401);
  await login(host, slug, hostEmail, changed); await expect(host).toHaveURL(new RegExp(`/${slug}/account$`));
  await page.screenshot({ path: testInfo.outputPath('admin-accounts.png'), fullPage: true }); expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  await page.getByRole('link', { name: 'Back to tenant', exact: true }).click(); await page.getByRole('button', { name: 'Delete tenant', exact: true }).click(); await expect(page.getByRole('group', { name: 'Confirm tenant deletion' })).toContainText(name); await page.getByRole('button', { name: 'Confirm deletion', exact: true }).press('Enter'); await expect(page).toHaveURL(/\/admin\/tenants$/);
  expect((await host.request.get(`/api/v1/t/${slug}`)).status()).toBe(404); expect((await host.request.get(`/api/v1/t/${slug}/listings/${listingId}`)).status()).toBe(404); expect((await host.request.get(`/api/v1/t/${slug}/auth/me`)).status()).toBe(404);
  const retained = await (await page.request.get(`/api/v1/admin/tenants/${tenantId}`)).json(); expect(retained.deletedAt).toBeTruthy(); expect(retained.slug).toBe(slug);
 } finally { await context.close(); }
 expect(errors).toEqual([]);
});
test('admin explicitly promotes a client with saved listings and assists another client with a password reset', async ({ page, browser, baseURL, browserErrors }, testInfo) => {
 test.setTimeout(90000); await administrator(page); const tenant = await (await page.request.get('/api/v1/t/greenstate')).json(); await page.goto(`/admin/tenants/${tenant.id}/accounts`);
 const context = await browser.newContext({ baseURL, viewport: page.viewportSize() }); const client = await context.newPage(); observeBrowserErrors(client, browserErrors); const email = `promote-client-${randomUUID()}@example.test`; const original = `Original client ${randomUUID()}!`; const temp = `Promotion temporary ${randomUUID()}!`;
 try {
  await register(client, email, original); const listings = await (await client.request.get('/api/v1/t/greenstate/listings?pageSize=1')).json(); const listing = listings.items[0]; await client.goto(`/greenstate/listings/${listing.id}`); await client.getByRole('button', { name: `Save ${listing.title}`, exact: true }).click(); await expect(client.getByRole('button', { name: `Remove ${listing.title} from saved listings`, exact: true })).toBeVisible();
  let row = await searchAccount(page, email); await row.getByRole('button', { name: 'Promote to host', exact: true }).click(); await expect(page.getByText(/Promotion grants host permissions/)).toBeVisible(); await page.getByLabel('Temporary password', { exact: true }).fill(temp); await page.getByLabel(/I verified.*identity/).check(); await page.getByRole('button', { name: 'Confirm promotion', exact: true }).click(); await expect(page.getByText(/Client promoted\./)).toBeVisible(); expect((await client.request.get('/api/v1/t/greenstate/auth/me')).status()).toBe(401);
  await login(client, 'greenstate', email, temp); await expect(client).toHaveURL(/\/greenstate\/password/); await client.goto('/greenstate/host/listings'); await expect(client).toHaveURL(/\/greenstate\/password/); await changePassword(client, temp, `Promoted password ${randomUUID()}!`, 'greenstate'); await client.getByRole('link', { name: 'Host workspace', exact: true }).click(); await expect(client.getByRole('heading', { name: 'Your inventory', exact: true })).toBeVisible(); await client.getByRole('navigation', { name: 'Main navigation' }).getByRole('link', { name: 'Saved listings', exact: true }).click(); await expect(client.getByRole('link', { name: listing.title, exact: true })).toBeVisible();
  await client.goto('/greenstate/account'); await client.getByRole('button', { name: 'Sign out', exact: true }).click(); await expect(client).toHaveURL(/\/greenstate\/login(?:\?|$)/); const resetEmail = `reset-client-${randomUUID()}@example.test`; await register(client, resetEmail, original); await client.goto(`/greenstate/listings/${listing.id}`); await client.getByRole('button', { name: `Save ${listing.title}`, exact: true }).click(); await expect(client.getByRole('button', { name: `Remove ${listing.title} from saved listings`, exact: true })).toBeVisible();
  row = await searchAccount(page, resetEmail); await row.getByRole('button', { name: 'Reset password', exact: true }).click(); await page.getByLabel('Temporary password', { exact: true }).fill(temp); await page.getByLabel(/I verified.*identity/).check(); await page.getByRole('button', { name: 'Confirm password reset', exact: true }).click(); await expect(page.getByText(/Password reset\. All sessions revoked/)).toBeVisible(); expect((await client.request.get('/api/v1/t/greenstate/auth/me')).status()).toBe(401);
  await login(client, 'greenstate', resetEmail, temp); await changePassword(client, temp, `Recovered client ${randomUUID()}!`, 'greenstate'); await client.getByRole('navigation', { name: 'Main navigation' }).getByRole('link', { name: 'Saved listings', exact: true }).click(); await expect(client.getByRole('link', { name: listing.title, exact: true })).toBeVisible(); await expect(client.getByRole('link', { name: 'Host workspace', exact: true })).not.toBeVisible();
  await page.screenshot({ path: testInfo.outputPath('admin-lifecycle.png'), fullPage: true }); expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
 } finally { await context.close(); }
});
