import { randomUUID } from 'node:crypto';
import { expect } from '@playwright/test';
import { test, provisionHostFixture } from './fixtures.js';
const shift = (day: string, count: number) => new Date(Date.parse(day) + count * 86400000).toISOString().slice(0, 10);
const label = (day: string) => new Intl.DateTimeFormat('en-GB', { day: 'numeric', month: 'long', year: 'numeric', timeZone: 'UTC' }).format(new Date(day));
test('host edits a property range in the shared calendar and preserves its view', async ({ page }, testInfo) => {
  const tenant = await (await page.request.get('/api/v1/t/greenstate')).json();
  const host = await provisionHostFixture(tenant.id);
  await page.goto('/greenstate/login'); await page.getByLabel('Email', { exact: true }).fill(host.email); await page.getByLabel('Password', { exact: true }).fill(host.password);
  await page.getByRole('button', { name: 'Sign in', exact: true }).click(); await expect(page).toHaveURL(/\/password/);
  await page.getByLabel('Current password', { exact: true }).fill(host.password); await page.getByLabel('New password', { exact: true }).fill(`Changed portfolio ${randomUUID()}!`);
  await page.getByRole('button', { name: 'Change password', exact: true }).click(); await expect(page).toHaveURL(/\/host\/listings$/);
  const title = `Portfolio test ${randomUUID()}`;
  const headers = { Origin: new URL(page.url()).origin, 'X-Requested-By': 'greenstate-web' };
  const created = await page.request.post('/api/v1/t/greenstate/host/listings', { headers, data: { title, description: 'A portfolio calendar test property.', city: 'Berlin', country: 'DE', latitude: 52.52, longitude: 13.4, propertyType: 'apartment', maxGuests: 4, bedrooms: 2, pricePerNightCents: 12000 } });
  expect(created.status()).toBe(201); const listing = await created.json();
  const secondResponse = await page.request.post('/api/v1/t/greenstate/host/listings', { headers, data: { title: `${title} second`, description: null, city: 'Berlin', country: 'DE', latitude: 52.52, longitude: 13.4, propertyType: 'studio', maxGuests: 2, bedrooms: 1, pricePerNightCents: 9000 } });
  expect(secondResponse.status()).toBe(201); const second = await secondResponse.json();
  const publicPage = await (await page.request.get('/api/v1/t/greenstate/listings?pageSize=1')).json(); const from = shift(publicPage.today, 2); const last = shift(from, 2);
  await page.goto(`/greenstate/host/calendar?from=${from}&search=${encodeURIComponent(title)}`);
  await expect(page.getByRole('table', { name: 'Portfolio availability' }).getByRole('row')).toHaveCount(3);
  await page.getByRole('button', { name: `${title}, ${label(from)}, available`, exact: true }).click();
  await page.getByLabel('Last night (included)', { exact: true }).fill(last);
  await page.getByLabel('Reason (optional)', { exact: true }).fill('Prepare for guests');
  await expect(page.getByText('3 nights will be blocked', { exact: true })).toBeVisible();
  const save = page.getByRole('button', { name: 'Block 3 nights', exact: true });
  await save.scrollIntoViewIfNeeded(); await save.focus();
  const timeline = page.getByRole('region', { name: 'Property availability timeline', includeHidden: true });
  await timeline.evaluate(element => { element.scrollLeft = 120; });
  const beforeSave = await timeline.evaluate(element => ({ left: element.scrollLeft, top: element.scrollTop, pageY: window.scrollY }));
  expect(beforeSave.left).toBeGreaterThan(0);
  expect(beforeSave.pageY).toBeGreaterThan(0);
  // Keyboard submission keeps Playwright from changing scroll as part of pointer actionability.
  await save.press('Enter');
  await expect(page.getByText('3 nights blocked.', { exact: true })).toBeVisible();
  await expect(page.getByRole('button', { name: 'Remove 3 blocks', exact: true })).toBeVisible();
  const afterSave = await timeline.evaluate(element => ({ left: element.scrollLeft, top: element.scrollTop, pageY: window.scrollY }));
  expect(afterSave.left).toBeCloseTo(beforeSave.left, 0);
  expect(afterSave.top).toBeCloseTo(beforeSave.top, 0);
  expect(afterSave.pageY).toBeCloseTo(beforeSave.pageY, 0);
  const availability = await (await page.request.get(`/api/v1/t/greenstate/listings/${listing.id}/availability?from=${from}&to=${shift(last, 1)}`)).json();
  expect(availability.days.map((day: { available: boolean }) => day.available)).toEqual([false, false, false]);
  expect(new URL(page.url()).searchParams.get('search')).toBe(title);
  await page.screenshot({ path: testInfo.outputPath('portfolio-range.png'), fullPage: true });
  await page.getByRole('button', { name: 'Remove 3 blocks', exact: true }).click();
  await expect(page.getByText('3 blocks removed.', { exact: true })).toBeVisible();
  await page.getByRole('button', { name: 'Close availability editor', exact: true }).click();
  await expect(page.getByRole('button', { name: `${title}, ${label(from)}, available`, exact: true })).toBeFocused();
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  await page.getByRole('button', { name: `${title} second, ${label(shift(from, 3))}, available`, exact: true }).click();
  await page.getByLabel('Last night (included)', { exact: true }).fill(shift(from, 4));
  await page.getByRole('button', { name: 'Block 2 nights', exact: true }).click();
  await expect(page.getByText('2 nights blocked.', { exact: true })).toBeVisible();
  await page.getByRole('button', { name: 'Remove 2 blocks', exact: true }).click();
  await expect(page.getByText('2 blocks removed.', { exact: true })).toBeVisible();
  await page.getByRole('button', { name: 'Close availability editor', exact: true }).click();
  await page.screenshot({ path: testInfo.outputPath('portfolio-overview.png'), fullPage: true });
  await page.request.post(`/api/v1/t/greenstate/host/listings/${second.id}/archive`, { headers, data: { version: second.version } });
  await page.request.post(`/api/v1/t/greenstate/host/listings/${listing.id}/archive`, { headers, data: { version: listing.version } });
  await page.goto('/greenstate/host/calendar?pageSize=20');
  await expect(page.getByRole('table', { name: 'Portfolio availability' }).getByRole('row')).toHaveCount(21);
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  await page.screenshot({ path: testInfo.outputPath('portfolio-full-page.png'), fullPage: true });

});
