import { AccountActionDialog } from './AccountActionDialog';
import { useEffect, useRef, useState } from 'react';
import { Link, useSearchParams } from 'react-router-dom';
import { useQuery } from '@tanstack/react-query';
import { AccountsPageSchema, AccountsQuerySchema, type AdminTenant, type TenantAccount } from '@greenstate/contracts';
import { useAuth } from '../auth/AuthProvider';
import { RequirePermission } from '../auth/RequirePermission';
import { FormFeedback } from '../auth/AuthForm';
import { api } from '../../lib/api';
import { ErrorScreen } from '../../app/ErrorScreen';
import { Pagination } from '../../components/Pagination';
import { TenantResource, tenantsApi, useAdminInvalidation, useAdminRequest } from './shared';
import { HostForm } from './HostForm';
import { ResetPasswordForm } from './ResetPasswordForm';
type Action = { kind: 'create' } | { kind: 'reset' | 'promote' | 'disable' | 'enable'; account: TenantAccount } | null;
export function AccountsPage() { return <RequirePermission permission="accounts:manage"><TenantResource>{tenant => tenant.deletedAt ? <section><h1>Tenant unavailable</h1><p>This tenant is deleted. Account access is disabled and its records are retained.</p></section> : <Accounts key={tenant.id} tenant={tenant} />}</TenantResource></RequirePermission>; }
function Accounts({ tenant }: { tenant: AdminTenant }) {
 const auth = useAuth(); const [params, setParams] = useSearchParams(); const [action, setAction] = useState<Action>(null); const [message, setMessage] = useState(''); const invalidate = useAdminInvalidation();
 const heading = useRef<HTMLHeadingElement>(null);
 useEffect(() => { if (!action && message) heading.current?.focus({ preventScroll: true }); }, [action, message]);
 const parsed = AccountsQuerySchema.safeParse(Object.fromEntries(params)); const filters = parsed.success ? parsed.data : null;
 const query = useQuery({ queryKey: [...auth.privateKey!, 'admin-accounts', tenant.id, filters], enabled: !!filters, queryFn: ({ signal }) => api.get(`${tenantsApi}/${tenant.id}/accounts`, filters!, AccountsPageSchema, signal) });
 const done = (text: string) => { setAction(null); setMessage(text); invalidate(); };
 if (!parsed.success) return <section role="alert"><h1>Check account filters</h1><button className="button-secondary" onClick={() => setParams({})}>Reset filters</button></section>;
 return <section><Link className="back-link" to={`/admin/tenants/${tenant.id}`}>Back to tenant</Link><div className="host-heading"><div><p className="eyebrow">Platform administration</p><h1 id="accounts-heading" ref={heading} tabIndex={-1}>{tenant.name} accounts</h1><p>Provision hosts and manage access. Account shortlists remain private.</p></div><button className="button-primary" onClick={() => { setAction({ kind: 'create' }); setMessage(''); }}>Create host</button></div>
 {message && <p role="status" className="host-success">{message}</p>}
 {action && <AccountDialog key={`${tenant.id}:${action.kind}:${'account' in action ? action.account.id : ''}`} action={action} tenant={tenant} onDone={done} onClose={() => setAction(null)} onExisting={email => { setAction(null); setParams({ email, page: '1' }); }} />}
 <form key={params.toString()} className="admin-filters" onSubmit={event => { event.preventDefault(); const form = new FormData(event.currentTarget); const email = String(form.get('email') ?? '').trim(); const role = String(form.get('role') ?? ''); setParams({ status: String(form.get('status')), page: '1', ...(email ? { email } : {}), ...(role ? { role } : {}) }); }}><div><label htmlFor="account-email">Search account email</label><input id="account-email" name="email" defaultValue={filters?.email ?? ''} maxLength={254} /></div><div><label htmlFor="account-role">Role</label><select id="account-role" name="role" defaultValue={filters?.role ?? ''}><option value="">All roles</option><option value="client">Client</option><option value="host">Host</option></select></div><div><label htmlFor="account-status">Account status</label><select id="account-status" name="status" defaultValue={filters?.status}><option value="all">All accounts</option><option value="enabled">Enabled</option><option value="disabled">Disabled</option></select></div><button className="button-secondary">Apply filters</button></form>
 {query.isPending && <p role="status">Loading accounts…</p>}{query.isError && <ErrorScreen error={query.error} onRetry={() => { void query.refetch(); }} />}
 {query.data && <><p role="status">{query.data.total} {query.data.total === 1 ? 'account' : 'accounts'}</p>{query.data.items.length ? <div className="host-table-scroll"><table className="host-table"><caption className="host-sr-only">Tenant account metadata</caption><thead><tr><th>Account</th><th>Role</th><th>Status</th><th>Access actions</th></tr></thead><tbody>{query.data.items.map(account => <tr key={account.id}><th scope="row">{account.email}{account.name && <small className="admin-account-name">{account.name}</small>}</th><td>{account.role === 'host' ? 'Host' : 'Client'}</td><td>{account.disabledAt ? 'Disabled' : 'Enabled'}{account.mustChangePassword && <small className="admin-account-name">Password change required</small>}</td><td><div className="admin-row-actions"><button className="button-secondary" onClick={() => { setMessage(''); setAction({ kind: 'reset', account }); }}>Reset password</button>{account.role === 'client' ? <button className="button-secondary" onClick={() => { setMessage(''); setAction({ kind: 'promote', account }); }}>Promote to host</button> : <button className="button-secondary" onClick={() => { setMessage(''); setAction({ kind: account.disabledAt ? 'enable' : 'disable', account }); }}>{account.disabledAt ? 'Re-enable' : 'Disable'}</button>}</div></td></tr>)}</tbody></table></div> : <div className="empty-state"><h2>No accounts on this page</h2><p>Adjust your filters or create a host account.</p></div>}<Pagination {...query.data} onChange={page => { const next = new URLSearchParams(params); next.set('page', String(page)); setParams(next); }} /></>}
 </section>;
}

function AccountDialog({ action, tenant, onDone, onClose, onExisting }: { action: NonNullable<Action>; tenant: AdminTenant; onDone: (message: string) => void; onClose: () => void; onExisting: (email: string) => void }) {
 const request = useAdminRequest(); const [formBusy, setFormBusy] = useState(false);
 return <AccountActionDialog title={{ create: 'Create host', reset: 'Reset password', promote: 'Promote to host', disable: 'Disable host', enable: 'Re-enable host' }[action.kind]} tenant={tenant} busy={request.busy || formBusy} onClose={onClose}><FormFeedback problem={request.feedback.problem} />
 {action.kind === 'create' && <HostForm onBusy={setFormBusy} tenantId={tenant.id} onSuccess={() => onDone('Host created. A password change is required at first sign-in.')} onCancel={onClose} onExisting={onExisting} />}
 {(action.kind === 'reset' || action.kind === 'promote') && <ResetPasswordForm onBusy={setFormBusy} account={action.account} mode={action.kind} onCancel={onClose} onSuccess={() => onDone(action.kind === 'promote' ? 'Client promoted. All sessions revoked; a password change is required.' : 'Password reset. All sessions revoked; a password change is required.')} />}
 {(action.kind === 'disable' || action.kind === 'enable') && <section className="admin-action" role="group" aria-label="Confirm host access change"><h2>{action.kind === 'disable' ? 'Disable host' : 'Re-enable host'}</h2><p>{action.account.email}</p><p>{action.kind === 'disable' ? 'The entire tenant account will be disabled and all sessions revoked. Its data is retained.' : 'The host can sign in again. Revoked sessions stay invalid and any required password change remains in place.'}</p><div className="host-actions"><button className="button-secondary" disabled={request.busy} onClick={() => { void request.run(async signal => { await api.post(`${tenantsApi}/${tenant.id}/accounts/${action.account.id}/${action.kind}`, undefined, undefined, signal); if (signal.aborted) return; onDone(action.kind === 'disable' ? 'Host disabled. All sessions revoked.' : 'Host re-enabled. Sign in again to continue.'); }); }}>{action.kind === 'disable' ? 'Confirm disable' : 'Confirm re-enable'}</button><button className="button-secondary" disabled={request.busy} onClick={onClose}>Cancel</button></div></section>}
 </AccountActionDialog>;
}
